---
title: "RPackage"
output: html_document
---

```{r}
install.packages(c("devtools", "roxygen2","usethis","testthat","knitr"))
```

```{r}
library(devtools)
has_devel()
```

```{r}
# devtools::create_package() has been deprecated
# set your directory
# setwd()
usethis::create_package( "montyhall" )
```

```{r}
#' @title
#'   Create a new Monty Hall Problem game.
#'
#' @description
#'   `create_game()` generates a new game that consists of two doors 
#'   with goats behind them, and one with a car.
#'
#' @details
#'   The game setup replicates the game on the TV show "Let's
#'   Make a Deal" where there are three doors for a contestant
#'   to choose from, one of which has a car behind it and two 
#'   have goats. The contestant selects a door, then the host
#'   opens a door to reveal a goat, and then the contestant is
#'   given an opportunity to stay with their original selection
#'   or switch to the other unopened door. There was a famous 
#'   debate about whether it was optimal to stay or switch when
#'   given the option to switch, so this simulation was created
#'   to test both strategies. 
#'
#' @param ... no arguments are used by the function.
#' 
#' @return The function returns a length 3 character vector
#'   indicating the positions of goats and the car.
#'
#' @examples
#'   create_game()
#'
#' @export
create_game <- function()
{
    a.game <- sample( x=c("goat","goat","car"), size=3, replace=F )
    return( a.game )
} 



#' @title
#' @description
#' @details
#' @param 
#' @return 
#' @examples
#' @export
select_door <- function( )
{
  doors <- c(1,2,3) 
  a.pick <- sample( doors, size=1 )
  return( a.pick )  # number between 1 and 3
}
```

```{r}
getwd()
```


```{r}
setwd( "C:/Users/jtroger1/Documents/" )
devtools::install( "montyhall" )

```


